//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiPlagiarism_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class antiplagiarism_dbEntities : DbContext
    {
        public antiplagiarism_dbEntities()
            : base("name=antiplagiarism_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<about> abouts { get; set; }
        public virtual DbSet<approval_detail> approval_detail { get; set; }
        public virtual DbSet<approval_header> approval_header { get; set; }
        public virtual DbSet<approval_scheme> approval_scheme { get; set; }
        public virtual DbSet<approval_scheme_detail> approval_scheme_detail { get; set; }
        public virtual DbSet<classroom> classrooms { get; set; }
        public virtual DbSet<classroom_detail> classroom_detail { get; set; }
        public virtual DbSet<classroom_upload> classroom_upload { get; set; }
        public virtual DbSet<how> hows { get; set; }
        public virtual DbSet<journal_category> journal_category { get; set; }
        public virtual DbSet<journal_storage> journal_storage { get; set; }
        public virtual DbSet<local_compareList> local_compareList { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<slider> sliders { get; set; }
        public virtual DbSet<upload_check> upload_check { get; set; }
        public virtual DbSet<upload_check_detail> upload_check_detail { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<web_compareList> web_compareList { get; set; }
        public virtual DbSet<v_classroom> v_classroom { get; set; }
    }
}
