//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiPlagiarism_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class approval_header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public approval_header()
        {
            this.approval_detail = new HashSet<approval_detail>();
        }
    
        public long approvalID { get; set; }
        public string apvType { get; set; }
        public Nullable<long> keyID { get; set; }
        public string keyNm { get; set; }
        public Nullable<long> ID_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<short> is_finish { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approval_detail> approval_detail { get; set; }
        public virtual user user { get; set; }
    }
}
