//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiPlagiarism_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class approval_detail
    {
        public long detailID { get; set; }
        public Nullable<long> approvalID { get; set; }
        public Nullable<int> seq_no { get; set; }
        public string apv_next { get; set; }
        public string is_approved { get; set; }
        public Nullable<long> apv_by { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
    
        public virtual approval_header approval_header { get; set; }
    }
}
