//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiPlagiarism_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class classroom_upload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public classroom_upload()
        {
            this.upload_check = new HashSet<upload_check>();
        }
    
        public long uploadID { get; set; }
        public Nullable<long> classID { get; set; }
        public string journalTitle { get; set; }
        public string info { get; set; }
        public string author { get; set; }
        public string journalPath { get; set; }
        public Nullable<decimal> filesize { get; set; }
        public Nullable<int> pageCount { get; set; }
        public Nullable<long> wordCount { get; set; }
        public Nullable<long> characterCount { get; set; }
        public Nullable<decimal> similarityIndex { get; set; }
        public Nullable<int> similarityCount { get; set; }
        public string grading { get; set; }
        public Nullable<short> hasGraded { get; set; }
        public string response { get; set; }
        public Nullable<System.DateTime> uploadDt { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<long> ID_user { get; set; }
    
        public virtual classroom classroom { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upload_check> upload_check { get; set; }
    }
}
