//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiPlagiarism_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal_storage
    {
        public long storageID { get; set; }
        public string title { get; set; }
        public Nullable<long> categoryID { get; set; }
        public string info { get; set; }
        public string author { get; set; }
        public string filePath { get; set; }
        public Nullable<long> wordCount { get; set; }
        public Nullable<long> characterCount { get; set; }
        public string grading { get; set; }
        public Nullable<short> active { get; set; }
        public Nullable<System.DateTime> publishDt { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<long> ID_user { get; set; }
    
        public virtual journal_category journal_category { get; set; }
        public virtual user user { get; set; }
    }
}
