//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiPlagiarism_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public journal_category()
        {
            this.journal_storage = new HashSet<journal_storage>();
        }
    
        public long categoryID { get; set; }
        public string categoryNm { get; set; }
        public string info { get; set; }
        public Nullable<short> active { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<long> ID_user { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<journal_storage> journal_storage { get; set; }
    }
}
