//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiPlagiarism_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public long settingsID { get; set; }
        public Nullable<decimal> max_error_rate { get; set; }
        public Nullable<short> enable_web_compare { get; set; }
        public Nullable<short> enable_local_compare { get; set; }
        public Nullable<short> approval_system { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
