//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiPlagiarism_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slider
    {
        public long sliderID { get; set; }
        public string sliderTitle { get; set; }
        public string sliderHtml { get; set; }
        public string sliderImg { get; set; }
        public Nullable<short> active { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<long> ID_user { get; set; }
    
        public virtual user user { get; set; }
    }
}
