//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiPlagiarism_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class upload_check_detail
    {
        public long checkdetID { get; set; }
        public Nullable<long> checkID { get; set; }
        public Nullable<long> beginIndex { get; set; }
        public Nullable<long> endIndex { get; set; }
        public string colorText { get; set; }
        public Nullable<short> active { get; set; }
        public Nullable<decimal> similarityIndex { get; set; }
        public string notes { get; set; }
    
        public virtual upload_check upload_check { get; set; }
    }
}
