//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiPlagiarism_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class upload_check
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public upload_check()
        {
            this.upload_check_detail = new HashSet<upload_check_detail>();
        }
    
        public long checkID { get; set; }
        public Nullable<long> uploadID { get; set; }
        public string sourceCheck { get; set; }
        public Nullable<decimal> similarityIndex { get; set; }
        public Nullable<short> isLocal { get; set; }
    
        public virtual classroom_upload classroom_upload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upload_check_detail> upload_check_detail { get; set; }
    }
}
